### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by MickL** [gastonrobledo/handlebars-async-helpers#3]
Hello, I really appreciate your work but I wonder what the purpose of this library is over [LoicMahieu/handlebars-async](https://github.com/LoicMahieu/handlebars-async). Is there anything missing or not working in the other library? Or does this library make anything better than the other? 

Btw. there is a typo in your readme, it says `npm install handlerbars-async-helpers` instead of `npm install handlebars-async-helpers`

**Comment by gastonrobledo** [comment]
Hi @MickL, it is a totally different implementation, I have tried to use the other one first but that didn't work for me. The example on readme is not working, neither partials with async helpers on it. Fixed typo, thanks for that.

**Comment by MickL** [comment]
I see the other one is kinda outdated. I am trying yours out right now. You may write in the readme the purpose/motivation of this library (vs the other).
