### ISSUE TITLE
Is it really needed to use the patched variable?

### ISSUE THREAD

**Issue by MickL** [gastonrobledo/handlebars-async-helpers#6]
According to the readme, it is required to use the patched handlebars variable:

```
const handlebars = require('handlebars'),
      asyncHelpers = require('handlebars-async-helpers')

const asyncHandlebars = asyncHelpers(handlebars)
const template = asyncHandlebars.compile('123');
const rendered = await template({});
```

Anyway, to my testings it seems like this is not required, as even the original handlebars is now patched:

```
const handlebars = require('handlebars'),
      asyncHelpers = require('handlebars-async-helpers')

asyncHelpers(handlebars)

const template = handlebars.compile('123');
const rendered = await template({});
```

May you confirm? I wonder what method would be the best. By using handlebars at least we have type checking but compile() is not a Promise.

**Comment by gastonrobledo** [comment]
What version did you installed? latest one should not pollute the prototype.
